language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
before_script:
  - composer self-update
  - composer install --dev
mysql:
  database: zf2auth
  username: root
  encoding: utf8
script:
  - php vendor/bin/phpunit -c phpunit.xml  
after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v
before_install:
  - mysql -e 'drop database if exists zf2auth;'
  - mysql -e 'create database if not exists zf2auth;'
  - mysql -e 'show databases;'
  - mysql < datastructure/structure.sql