language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
before_script:
  - composer self-update
  - composer install --dev
mysql:
  database: zf2auth
  username: root
  encoding: utf8
before_install:
  - mysql -e 'drop database if exists zf2auth;'
  - mysql -e 'create database if not exists zf2auth;'
  - mysql -e 'show databases;'